# -*- coding: utf-8 -*-
"""maine1_v0.1_wrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPR7S2_dz8IXGqbJpo24jhxG7FS3TR9a
"""

# maine1_v0.1.py — now just a demo wrapper
from n2_overmind import run_n2_overmind
import os

print("\nMainE1 — N² Overmind v0.1 — Now reusable!\n")

history = ""
while True:
    query = input("QUERY → ").strip()
    if query.lower() in {"exit", "quit", ""}:
        break

    response = run_n2_overmind(query, history)
    print("\n" + response)
    history += f"\nUser: {query}\nMainE1: {response}"

    print("\n" + "—" * 80)