# -*- coding: utf-8 -*-
"""MainE1-N²-Overmind-V1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFHnUeNBZ3hMq9aO49x1rG7uFzFQ3LG1
"""

# n2_overmind.py
# The reusable N² Overmind core — MIT License (same as MainE1)
# Drop this file into any project and call run_n2_overmind(query, history="")

from crewai import Agent, Task, Crew
from langchain_openai import ChatOpenAI
import os
from typing import Dict, Any

# ====================== CONFIG ======================
ENABLE_N2_REFLECTION = True      # ← One-line toggle for A/B testing
DEBUG_SHOW_SCORE = False          # Set to True to see private scores + repairs live
MAX_REPAIR_LOOPS = 4
SCORE_THRESHOLD = 9
# ====================================================

llm = ChatOpenAI(model=os.getenv("OPENAI_MODEL", "gpt-5.1"), temperature=0.0)

# Lower layer — the magic 6 sub-personalities (exactly as in MainE1)
sub_agents = [
    Agent(role="Creative Clarity",      goal="Clear ideation",       backstory="Tone: clear, concise, factual. No fluff. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False),
    Agent(role="Structural Clarity",    goal="Relieve overload",     backstory="Tone: non-judgmental, reflective, straightforward. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False),
    Agent(role="Self-Alignment",        goal="Goal coherence",       backstory="Tone: sharp, minimal, focused. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False),
    Agent(role="Decision Support",      goal="Structured decisions", backstory="Tone: tactical, calm, analytical. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False),
    Agent(role="Recovery Management",  goal="Pressure relief",      backstory="Tone: firm yet empathetic. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False),
    Agent(role="Boundary Clarity",      goal="Define limits",        backstory="Tone: steady, respectful, firm. Output exactly 4 numbered SIM steps only.", llm=llm, allow_delegation=False, verbose=False),
]

central = Agent(
    role="Central Consciousness",
    goal="Produce one unified, perfect response",
    backstory="""You receive the outputs of exactly 6 sub-personalities. Never reveal their names or internal process.
Run ODAI once:
Observation → Distillation (core truth + alignment score 0–10) → Adaptation (if <8 write repair) → Integration (if ≥8 write final markdown)
If score ≥8 → output ONLY the final answer in clean markdown.
If score <8 → output ONLY repair instructions.
Never output JSON or mention score unless DEBUG_SHOW_SCORE is True.""",
    llm=llm,
    verbose=False
)

def run_n2_overmind(query: str, history: str = "") -> str:
    """Call this function from any IDE/agent — returns the final clean answer."""
    if not ENABLE_N2_REFLECTION:
        # Bypass N² entirely — useful for A/B testing speed vs quality
        task = Task(description=query + "\n\n" + history, expected_output="Clean markdown response.", agent=central)
        return Crew(agents=[central], tasks=[task], verbose=False).kickoff().raw

    full_query = query + "\n\nConversation history:\n" + history

    # First pass
    tasks = [Task(description=full_query, expected_output="Exactly 4 numbered SIM lines only.", agent=a) for a in sub_agents]
    contributions = Crew(agents=sub_agents, tasks=tasks, verbose=False).kickoff().raw

    for attempt in range(1, MAX_REPAIR_LOOPS + 1):
        synth_task = Task(
            description=f"User query: {query}\nSub-personality contributions:\n{contributions}",
            expected_output="JSON with keys: score (int), repair (str or null), final (str or null)",
            agent=central
        )
        result = Crew(agents=[central], tasks=[synth_task], verbose=False).kickoff().raw

        if DEBUG_SHOW_SCORE and "score" in result.lower():
            print(f"\n[Debug] N² private score: {result}")

        try:
            data = eval(result.strip())
            score = int(data.get("score", 0))

            if score >= SCORE_THRESHOLD:
                final = data.get("final") or data.get("synthesis") or result
                if DEBUG_SHOW_SCORE:
                    print(f"✓ N² Accepted at {score}/10 after {attempt} attempt(s)")
                return final.strip()
            else:
                repair = data.get("repair", "Improve clarity and alignment.")
                if DEBUG_SHOW_SCORE:
                    print(f"✗ N² Rejected (score {score}/10) → Repairing...")
                # Repair loop
                repair_tasks = [Task(description=query + "\nREPAIR: " + repair, expected_output="Exactly 4 numbered SIM lines only.", agent=a) for a in sub_agents]
                contributions = Crew(agents=sub_agents, tasks=repair_tasks, verbose=False).kickoff().raw
        except:
            continue

    # Fallback
    return result.strip()